// AI Provider Icons - Local imports
// Downloaded from LobeHub Icons (https://lobehub.com/icons)

export const providerIcons = {
  openai: () => import('./provider-icons/openai.png'),
  anthropic: () => import('./provider-icons/anthropic.png'),
  deepseek: () => import('./provider-icons/deepseek.png'),
  google: () => import('./provider-icons/google.png'),
  xai: () => import('./provider-icons/xai.png'),
  openrouter: () => import('./provider-icons/openrouter.png'),
  alibabacloud: () => import('./provider-icons/alibabacloud.png'),
  groq: () => import('./provider-icons/groq.png'),
  huggingface: () => import('./provider-icons/huggingface.png'),
  minimax: () => import('./provider-icons/minimax.png'),
  moonshot: () => import('./provider-icons/moonshot.png'),
  zhipu: () => import('./provider-icons/zhipu.png'),
  ollama: () => import('./provider-icons/ollama.png'),
  vllm: () => import('./provider-icons/vllm.png'),
  lmstudio: () => import('./provider-icons/lmstudio.png'),
  together: () => import('./provider-icons/together.png'),
  anyscale: () => import('./provider-icons/anyscale.png'),
  perplexity: () => import('./provider-icons/perplexity.png'),
  mistral: () => import('./provider-icons/mistral.png'),
  cohere: () => import('./provider-icons/cohere.png'),
  fireworks: () => import('./provider-icons/fireworks.png'),
  replicate: () => import('./provider-icons/replicate.png'),
  nvidia: () => import('./provider-icons/nvidia.png'),
  ibm: () => import('./provider-icons/ibm.png'),
  azure: () => import('./provider-icons/azure.png'),
  bedrock: () => import('./provider-icons/bedrock.png'),
  cloudflare: () => import('./provider-icons/cloudflare.png'),
  cerebras: () => import('./provider-icons/cerebras.png'),
  friendli: () => import('./provider-icons/friendli.png'),
  novita: () => import('./provider-icons/novita.png'),
  sambanova: () => import('./provider-icons/sambanova.png'),
}

// 提供商名称映射
export const providerNames: Record<string, string> = {
  openai: 'OpenAI',
  anthropic: 'Anthropic',
  deepseek: 'DeepSeek',
  google: 'Google Gemini',
  xai: 'xAI / Grok',
  openrouter: 'OpenRouter',
  alibabacloud: 'Qwen (DashScope)',
  groq: 'Groq',
  huggingface: 'Hugging Face',
  minimax: 'MiniMax',
  moonshot: 'Kimi / Moonshot',
  zhipu: 'Z.AI / GLM',
  ollama: 'Ollama (本地)',
  vllm: 'vLLM',
  lmstudio: 'LM Studio',
  together: 'Together AI',
  anyscale: 'Anyscale',
  perplexity: 'Perplexity',
  mistral: 'Mistral AI',
  cohere: 'Cohere',
  fireworks: 'Fireworks AI',
  replicate: 'Replicate',
  nvidia: 'NVIDIA NIM',
  ibm: 'IBM Watsonx',
  azure: 'Azure OpenAI',
  bedrock: 'Amazon Bedrock',
  cloudflare: 'Cloudflare AI',
  cerebras: 'Cerebras',
  friendli: 'FriendliAI',
  novita: 'Novita AI',
  sambanova: 'SambaNova',
}
